POST http://localhost:3003/api/pom
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYWZiM2FlYzM5YTc0NzcxMmJkOGZlOSIsImlhdCI6MTYyMzA1MjI2Mn0.FfatK0Fnybo1Rbr1v2hloC8jRdBjVE4SmmNj63CMbO0

{
"todo": "Oh my chips",
"status": false
}